# Project- Sentiment Analysis

# Resturant Coustomer FeedBack Analysis

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing dataset

In [66]:
dataset=pd.read_csv(r"C:\Users\umari\OneDrive\Desktop\FSDS DATASETs\Restaurant_Reviews.tsv",delimiter='\t',quoting=3)

In [67]:
dataset

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

# Cleaning The Texts

In [68]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [69]:
corpus=[]

In [70]:
for i in range(0,1000):
    review=re.sub('[^a-zA-Z]',' ',dataset['Review'][i])
    review=review.lower()
    review=review.split()
    ps=PorterStemmer()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

# Creating the Bag of Word Model

In [71]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X= cv.fit_transform(corpus).toarray()

In [72]:
# from sklearn.feature_extraction.text import TfidfTransformer
# Tf= TfidfTransformer()
# X= cv.fit_transform(corpus).toarray()

In [73]:
y= dataset.iloc[:,1].values 

# Splitting the dataset into the Training Set and Test Set

In [74]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [75]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

# Predicting the Test Set Result

In [76]:
y_pred= classifier.predict(X_test)

# Making the Confusion Matrix

In [77]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)
print(cm)

[[73 24]
 [44 59]]


In [78]:
from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test,y_pred)
print(accuracy)

0.66


In [79]:
bias=classifier.score(X_train,y_train)
bias

0.99625

In [80]:
varience=classifier.score(X_test,y_test)
varience

0.66

In [81]:
import nltk
dir(nltk)

['ARLSTem',
 'ARLSTem2',
 'AbstractLazySequence',
 'AffixTagger',
 'AlignedSent',
 'Alignment',
 'AnnotationTask',
 'ApplicationExpression',
 'Assignment',
 'BigramAssocMeasures',
 'BigramCollocationFinder',
 'BigramTagger',
 'BinaryMaxentFeatureEncoding',
 'BlanklineTokenizer',
 'BllipParser',
 'BottomUpChartParser',
 'BottomUpLeftCornerChartParser',
 'BottomUpProbabilisticChartParser',
 'Boxer',
 'BrillTagger',
 'BrillTaggerTrainer',
 'CFG',
 'CRFTagger',
 'CfgReadingCommand',
 'ChartParser',
 'ChunkParserI',
 'ChunkScore',
 'Cistem',
 'ClassifierBasedPOSTagger',
 'ClassifierBasedTagger',
 'ClassifierI',
 'ConcordanceIndex',
 'ConditionalExponentialClassifier',
 'ConditionalFreqDist',
 'ConditionalProbDist',
 'ConditionalProbDistI',
 'ConfusionMatrix',
 'ContextIndex',
 'ContextTagger',
 'ContingencyMeasures',
 'CoreNLPDependencyParser',
 'CoreNLPParser',
 'CrossValidationProbDist',
 'DRS',
 'DecisionTreeClassifier',
 'DefaultTagger',
 'DependencyEvaluator',
 'DependencyGrammar',
 'D

# Selecting a Model and traing it

In [82]:
# ✅ Importing required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

# ✅ Download NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')

# ✅ Load your dataset
# Example: feedback.csv should have columns: 'feedback' (text) and 'sentiment' (Positive/Negative/Neutral)
df = pd.read_csv(r"C:\Users\umari\OneDrive\Desktop\FSDS DATASETs\Restaurant_Reviews.tsv", sep='\t')

# ✅ Rename columns to match our pipeline
df.rename(columns={'Review': 'feedback', 'Liked': 'sentiment'}, inplace=True)

# ✅ Basic text preprocessing
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()  # Lowercase
    text = ''.join([ch for ch in text if ch not in string.punctuation])  # Remove punctuation
    words = text.split()
    words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]  # Remove stopwords + Lemmatize
    return ' '.join(words)

df['cleaned_feedback'] = df['feedback'].apply(clean_text)

# ✅ Feature extraction using TF-IDF
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X = tfidf.fit_transform(df['cleaned_feedback'])
y = df['sentiment']

# ✅ Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ✅ Initialize and train SVM model
svm = LinearSVC()
svm.fit(X_train, y_train)

# ✅ Make predictions
y_pred = svm.predict(X_test)

# ✅ Evaluate model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.78

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.85      0.79        96
           1       0.84      0.71      0.77       104

    accuracy                           0.78       200
   macro avg       0.79      0.78      0.78       200
weighted avg       0.79      0.78      0.78       200


Confusion Matrix:
 [[82 14]
 [30 74]]


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\umari\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\umari\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [83]:
# ✅ Hyperparameter Tuning using GridSearchCV for SVM
from sklearn.model_selection import GridSearchCV
from sklearn.svm import LinearSVC

# Define the SVM model
svm = LinearSVC()

# Define parameter grid for tuning
param_grid = {
    'C': [0.01, 0.1, 1, 10],          # Regularization strength
    'max_iter': [1000, 2000, 3000]    # Iterations for convergence
}

# Initialize GridSearchCV
grid_search = GridSearchCV(
    estimator=svm,
    param_grid=param_grid,
    cv=5,                 # 5-fold cross-validation
    scoring='accuracy',
    n_jobs=-1,            # Use all CPU cores
    verbose=2
)

# Fit GridSearchCV on training data
grid_search.fit(X_train, y_train)

# Best parameters and best estimator
print("✅ Best Parameters Found:", grid_search.best_params_)
best_svm = grid_search.best_estimator_

# Predict using the best model
y_pred = best_svm.predict(X_test)

# Evaluate tuned model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("\n📊 Tuned Model Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Fitting 5 folds for each of 12 candidates, totalling 60 fits
✅ Best Parameters Found: {'C': 1, 'max_iter': 1000}

📊 Tuned Model Accuracy: 0.78

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.85      0.79        96
           1       0.84      0.71      0.77       104

    accuracy                           0.78       200
   macro avg       0.79      0.78      0.78       200
weighted avg       0.79      0.78      0.78       200


Confusion Matrix:
 [[82 14]
 [30 74]]


In [84]:
svm.fit(X_train,y_train)

LinearSVC()

In [85]:
svm.coef_

array([[-0.466765  , -0.27892152, -0.1024428 , ...,  0.44236963,
        -0.57829848, -0.4729568 ]], shape=(1, 5000))

In [86]:
svm.intercept_

array([-0.10365562])

In [87]:
# ✅ Example: Predict sentiment for a new customer review
new_review = ["The food was delicious and the service was excellent!"]

# Clean and vectorize the new review
cleaned = [clean_text(new_review[0])]
vectorized = tfidf.transform(cleaned)

# Predict sentiment using your trained SVM model
prediction = best_svm.predict(vectorized)
print("Predicted Sentiment:", prediction[0])


Predicted Sentiment: 1


In [88]:
print("Predicted Sentiment:", "Positive 😀" if prediction[0] == 1 else "Negative 😞")


Predicted Sentiment: Positive 😀


In [89]:
new_review = ["The ambience was amazing and the staff were friendly!"]
cleaned = [clean_text(new_review[0])]
vectorized = tfidf.transform(cleaned)
prediction = best_svm.predict(vectorized)

print("Predicted Sentiment:", "Positive 😀" if prediction[0] == 1 else "Negative 😞")


Predicted Sentiment: Positive 😀


In [90]:
y_pred = svm.predict(X_test)
y_pred


array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1])

In [91]:
# ✅ View actual vs predicted sentiment
result = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(result.head(10))


     Actual  Predicted
521       1          0
737       1          1
740       1          1
660       1          1
411       1          1
678       1          1
626       0          0
513       1          1
859       0          0
136       1          1


# Fine- Tune Your Model

In [92]:
svm.score(X_test, y_test)

0.78

# Present Your Solution 

# Save Ml Model

In [93]:
import joblib  

# Save both model and vectorizer
joblib.dump(svm, "restaurant_feedback_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")


['tfidf_vectorizer.pkl']

In [94]:
import joblib

# Load model and vectorizer
svm = joblib.load("restaurant_feedback_model.pkl")
tfidf = joblib.load("tfidf_vectorizer.pkl")

# Predict sentiment
new_feedback = ["The food was amazing and the service was great!"]
prediction = svm.predict(tfidf.transform(new_feedback))
print("Predicted Sentiment:", prediction[0])


Predicted Sentiment: 1


In [95]:
model= joblib.load("restaurant_feedback_model.pkl")

In [96]:
import os
os.getcwd()

'c:\\Users\\umari\\OneDrive\\Desktop\\FSDS Projects\\NLP-Project Coustomer FeedBack Analysis'